# Generated by Django 4.2.7 on 2023-11-16 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_bird'),
    ]

    operations = [
        migrations.CreateModel(
            name='Physio_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('body_part', models.CharField(choices=[('low back', 'Low Back'), ('neck', 'Neck'), ('shoulder', 'Shoulder'), ('elbow', 'Elbow'), ('wrist', 'Wrist'), ('hand', 'Hand'), ('hip', 'Hip'), ('knee', 'Knee'), ('ankle/foot', 'Ankle/Foot')], default=('low back', 'Low Back'), max_length=10)),
                ('time', models.IntegerField()),
                ('trauma', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('scans', models.CharField(max_length=100)),
                ('aggs', models.CharField(max_length=100)),
                ('eases', models.CharField(max_length=100)),
                ('past_treatment', models.CharField(max_length=100)),
                ('medication', models.CharField(max_length=100)),
                ('work', models.CharField(max_length=100)),
                ('goals', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('response', models.CharField()),
                ('physio_form_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.physio_form')),
            ],
        ),
    ]
