# Generated by Django 4.2.7 on 2023-11-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_physio_form_treatment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bird',
        ),
        migrations.DeleteModel(
            name='Cat',
        ),
        migrations.DeleteModel(
            name='Dog',
        ),
        migrations.AlterField(
            model_name='physio_form',
            name='time',
            field=models.IntegerField(verbose_name='Length of time of condition (months)'),
        ),
    ]
