# Generated by Django 4.2.7 on 2023-11-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_treatment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physio_form',
            name='body_part',
        ),
        migrations.AlterField(
            model_name='physio_form',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
