# Generated by Django 4.2.7 on 2023-11-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_physio_form_body_part_alter_physio_form_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='physio_form',
            name='treatment_complete',
            field=models.BooleanField(default=False),
        ),
    ]
