# Generated by Django 4.2.7 on 2023-11-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_physio_form_treatment_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='physio_form',
            name='body_part',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
