# Generated by Django 4.2.7 on 2023-11-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_physio_form_body_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physio_form',
            name='time',
            field=models.CharField(max_length=10),
        ),
    ]
