# Generated by Django 4.2.7 on 2023-11-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_physio_form_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='physio_form',
            name='name',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
