# Generated by Django 4.2.7 on 2023-11-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_physio_form_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='physio_form',
            name='age',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
    ]
